name: Update Packagist on Release

on:
  release:
    types: [published]

jobs:
  packagist:
    name: Notify Packagist
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Packagist Update
        run: |
          curl -X POST https://packagist.org/api/update-package \
            -H "Authorization: token ${{ secrets.PACKAGIST_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"repository\":{\"url\":\"https://github.com/${{ github.repository }}\"}}"
